name: Debug index.ts with npm run ts

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run npm run ts for debugging
      run: ts-node src/index.ts

    # Add additional steps here for debugging index.ts
    # For example:
    # - name: Display contents of index.ts
    #   run: cat src/index.ts
